# Generated by Semantic Layer Builder
# Project: semantic_layer_builder

connection: "bigquery_connection"
include: "/*.view.lkml"

explore: clients {
}

explore: orders {

  join: clients {
    type: left_outer
    relationship: many_to_one
    sql_on: ${orders.client_id} = ${clients.client_id} ;;
  }
}
